import {
  ID,
  OFF,
} from "../../_strings";

export const SvelteDisable = {
  id: ID.Disable.Disable,
  rules: {
    // ESLint core rules known to cause problems with `.svelte`.
    // DOC: https://github.com/sveltejs/eslint-plugin-svelte/blob/ca37fbbe82d01019946e12eeb1b57c2a5736c018/packages/eslint-plugin-svelte/src/configs/base.ts
    "no-inner-declarations": OFF /* The AST generated by svelte-eslint-parser will false positives in it rule because the root node of the script is not the `Program`. */,
    "no-self-assign": OFF /* Self assign is one of way to update reactive value in Svelte */,
    "no-unused-vars": OFF /* breaks use of svelte global */,
    "@typescript-eslint/no-unused-vars": OFF /* TS: breaks use of svelte global */,
    "prefer-const": OFF /* svelte/prefer-const */,
    // My own
    "@stylistic/indent": OFF /* Conflicts with `svelte/indent` */,
  } as const,
};
