import { State } from "./state";

export default {
  // The following rules can be used in some cases. See the README for more
  // information. These are marked with `0` instead of `"off"` so that a
  // script can distinguish them. Note that there are a few more of these
  // in the deprecated section below.
  curly: State.OFF,
  "no-unexpected-multiline": State.OFF,
  "stylistic/lines-around-comment": State.OFF,
  "stylistic/max-len": State.OFF,
  "stylistic/no-confusing-arrow": State.OFF,
  "stylistic/no-mixed-operators": State.OFF,
  "stylistic/no-tabs": State.OFF,
  "stylistic/quotes": State.OFF,

  // The rest are rules that you never need to enable when using Prettier.
  "stylistic/array-bracket-newline": State.OFF,
  "stylistic/array-bracket-spacing": State.OFF,
  "stylistic/array-element-newline": State.OFF,
  "stylistic/arrow-parens": State.OFF,
  "stylistic/arrow-spacing": State.OFF,
  "stylistic/block-spacing": State.OFF,
  "stylistic/brace-style": State.OFF,
  "stylistic/comma-dangle": State.OFF,
  "stylistic/comma-spacing": State.OFF,
  "stylistic/comma-style": State.OFF,
  "stylistic/computed-property-spacing": State.OFF,
  "stylistic/dot-location": State.OFF,
  "stylistic/eol-last": State.OFF,
  "stylistic/func-call-spacing": State.OFF,
  "stylistic/function-call-argument-newline": State.OFF,
  "stylistic/function-call-spacing": State.OFF,
  "stylistic/function-paren-newline": State.OFF,
  "stylistic/generator-star-spacing": State.OFF,
  "stylistic/implicit-arrow-linebreak": State.OFF,
  "stylistic/indent": State.OFF,
  "stylistic/key-spacing": State.OFF,
  "stylistic/keyword-spacing": State.OFF,
  "stylistic/linebreak-style": State.OFF,
  "stylistic/max-statements-per-line": State.OFF,
  "stylistic/multiline-ternary": State.OFF,
  "stylistic/new-parens": State.OFF,
  "stylistic/newline-per-chained-call": State.OFF,
  "stylistic/no-extra-parens": State.OFF,
  "stylistic/no-extra-semi": State.OFF,
  "stylistic/no-floating-decimal": State.OFF,
  "stylistic/no-mixed-spaces-and-tabs": State.OFF,
  "stylistic/no-multi-spaces": State.OFF,
  "stylistic/no-multiple-empty-lines": State.OFF,
  "stylistic/no-trailing-spaces": State.OFF,
  "stylistic/no-whitespace-before-property": State.OFF,
  "stylistic/nonblock-statement-body-position": State.OFF,
  "stylistic/object-curly-newline": State.OFF,
  "stylistic/object-curly-spacing": State.OFF,
  "stylistic/object-property-newline": State.OFF,
  "stylistic/one-var-declaration-per-line": State.OFF,
  "stylistic/operator-linebreak": State.OFF,
  "stylistic/padded-blocks": State.OFF,
  "stylistic/quote-props": State.OFF,
  "stylistic/rest-spread-spacing": State.OFF,
  "stylistic/semi": State.OFF,
  "stylistic/semi-spacing": State.OFF,
  "stylistic/semi-style": State.OFF,
  "stylistic/space-before-blocks": State.OFF,
  "stylistic/space-before-function-paren": State.OFF,
  "stylistic/space-in-parens": State.OFF,
  "stylistic/space-infix-ops": State.OFF,
  "stylistic/space-unary-ops": State.OFF,
  "stylistic/switch-colon-spacing": State.OFF,
  "stylistic/template-curly-spacing": State.OFF,
  "stylistic/template-tag-spacing": State.OFF,
  "stylistic/wrap-iife": State.OFF,
  "stylistic/wrap-regex": State.OFF,
  "stylistic/yield-star-spacing": State.OFF,
  "stylistic/member-delimiter-style": State.OFF,
  "stylistic/type-annotation-spacing": State.OFF,
  "stylistic/indent-binary-ops": State.OFF,
  "stylistic/type-generic-spacing": State.OFF,
  "stylistic/type-named-tuple-spacing": State.OFF,
};
