import { State } from "../state";

// DOC: https://typescript-eslint.io/rules/?=xextension-xdeprecated#rules
export default {
  name: "enable",
  rules: {
    // "@typescript-eslint/adjacent-overload-signatures": State.OFF,
    // "@typescript-eslint/array-type": State.OFF /* preference: ideally, I'd like to don't-care mutable arrays while requiring readonly [] syntax for immutable arrays, but there is no way to do that with the current rule options */,
    "@typescript-eslint/await-thenable": State.ON,
    "@typescript-eslint/ban-ts-comment": State.ON,
    "@typescript-eslint/ban-tslint-comment": State.ON,
    "@typescript-eslint/class-literal-property-style": State.ON,
    "@typescript-eslint/consistent-generic-constructors": State.ON,
    "@typescript-eslint/consistent-indexed-object-style": State.ON,
    "@typescript-eslint/consistent-type-assertions": [
      State.ON,
      {
        arrayLiteralTypeAssertions: "never",
        objectLiteralTypeAssertions: "never",
      },
    ],
    // "@typescript-eslint/consistent-type-definitions": State.OFF,
    "@typescript-eslint/consistent-type-exports": State.ON,
    "@typescript-eslint/consistent-type-imports": State.ON,
    // "@typescript-eslint/explicit-function-return-type": State.OFF,
    "@typescript-eslint/explicit-member-accessibility": [
      State.ON,
      {
        overrides: {
          constructors: "no-public",
        },
      },
    ],
    // "@typescript-eslint/explicit-module-boundary-types": State.OFF,
    "@typescript-eslint/member-ordering": [
      State.ON,
      {
        "default": {
          optionalityOrder: "required-first",
        },
      },
    ],
    "@typescript-eslint/method-signature-style": State.ON,
    // "@typescript-eslint/naming-convention": State.OFF,
    "@typescript-eslint/no-array-delete": State.ON,
    "@typescript-eslint/no-base-to-string": State.ON,
    "@typescript-eslint/no-confusing-non-null-assertion": State.ON,
    "@typescript-eslint/no-confusing-void-expression": State.ON,
    // "@typescript-eslint/no-deprecated": State.OFF /* incompatible: Cannot be used with jsDocParsingMode: "none" */,
    "@typescript-eslint/no-duplicate-enum-values": State.ON,
    "@typescript-eslint/no-duplicate-type-constituents": State.ON,
    "@typescript-eslint/no-dynamic-delete": State.ON,
    "@typescript-eslint/no-empty-object-type": State.ON,
    "@typescript-eslint/no-explicit-any": [
      State.ON,
      {
        fixToUnknown: true,
      },
    ],
    "@typescript-eslint/no-extra-non-null-assertion": State.ON,
    "@typescript-eslint/no-extraneous-class": [
      State.ON,
      {
        allowEmpty: true,
      },
    ],
    "@typescript-eslint/no-floating-promises": [
      State.ON,
      {
        checkThenables: true,
      },
    ],
    "@typescript-eslint/no-for-in-array": State.ON,
    "@typescript-eslint/no-import-type-side-effects": State.ON,
    "@typescript-eslint/no-inferrable-types": State.ON,
    // "@typescript-eslint/no-invalid-void-type": State.OFF /* preference - I powerfully ideologically disagree with disallowing void, a valid type */,
    "@typescript-eslint/no-meaningless-void-operator": [
      State.ON,
      {
        checkNever: true,
      },
    ],
    "@typescript-eslint/no-misused-new": State.ON,
    "@typescript-eslint/no-misused-promises": State.ON,
    "@typescript-eslint/no-misused-spread": State.ON,
    "@typescript-eslint/no-mixed-enums": State.ON,
    // "@typescript-eslint/no-namespace": State.OFF,
    "@typescript-eslint/no-non-null-asserted-nullish-coalescing": State.ON,
    "@typescript-eslint/no-non-null-asserted-optional-chain": State.ON,
    // "@typescript-eslint/no-non-null-assertion": State.OFF /* preference */,
    "@typescript-eslint/no-redundant-type-constituents": State.ON,
    // "@typescript-eslint/no-restricted-types": State.OFF /* preference - no shared custom types across all projects that I wish to ban */,
    "@typescript-eslint/no-require-imports": State.ON,
    "@typescript-eslint/no-this-alias": State.ON,
    "@typescript-eslint/no-unnecessary-boolean-literal-compare": State.ON,
    "@typescript-eslint/no-unnecessary-condition": State.ON,
    "@typescript-eslint/no-unnecessary-parameter-property-assignment": State.ON,
    "@typescript-eslint/no-unnecessary-qualifier": State.ON,
    "@typescript-eslint/no-unnecessary-template-expression": State.ON,
    "@typescript-eslint/no-unnecessary-type-arguments": State.ON,
    "@typescript-eslint/no-unnecessary-type-assertion": State.ON,
    "@typescript-eslint/no-unnecessary-type-constraint": State.ON,
    "@typescript-eslint/no-unnecessary-type-conversion": State.ON,
    "@typescript-eslint/no-unnecessary-type-parameters": State.ON,
    "@typescript-eslint/no-unsafe-argument": State.ON,
    "@typescript-eslint/no-unsafe-assignment": State.ON,
    "@typescript-eslint/no-unsafe-call": State.ON,
    "@typescript-eslint/no-unsafe-declaration-merging": State.ON,
    "@typescript-eslint/no-unsafe-enum-comparison": State.ON,
    "@typescript-eslint/no-unsafe-function-type": State.ON,
    "@typescript-eslint/no-unsafe-member-access": [
      State.ON,
      {
        allowOptionalChaining: true,
      },
    ],
    "@typescript-eslint/no-unsafe-return": State.ON,
    // "@typescript-eslint/no-unsafe-type-assertion": State.OFF,
    "@typescript-eslint/no-unsafe-unary-minus": State.ON,
    "@typescript-eslint/no-useless-empty-export": State.ON,
    "@typescript-eslint/no-wrapper-object-types": State.ON,
    // "@typescript-eslint/non-nullable-type-assertion-style": State.OFF /* preference */,
    "@typescript-eslint/parameter-properties": [
      State.ON,
      {
        prefer: "parameter-property" /* parameter-property | @default class-property */,
      },
    ],
    "@typescript-eslint/prefer-as-const": State.ON,
    // "@typescript-eslint/prefer-enum-initializers": State.OFF /* preference */,
    "@typescript-eslint/prefer-find": State.ON,
    "@typescript-eslint/prefer-for-of": State.ON,
    "@typescript-eslint/prefer-function-type": State.ON,
    "@typescript-eslint/prefer-includes": State.ON,
    "@typescript-eslint/prefer-literal-enum-member": State.ON,
    "@typescript-eslint/prefer-namespace-keyword": State.ON,
    "@typescript-eslint/prefer-nullish-coalescing": State.ON /* requires tsconfig: strictNullChecks */,
    "@typescript-eslint/prefer-optional-chain": State.ON,
    "@typescript-eslint/prefer-readonly": State.ON,
    // "@typescript-eslint/prefer-readonly-parameter-types": State.OFF /* preference - WAY too restrictive */,
    "@typescript-eslint/prefer-reduce-type-parameter": State.ON,
    "@typescript-eslint/prefer-regexp-exec": State.ON,
    "@typescript-eslint/prefer-return-this-type": State.ON,
    "@typescript-eslint/prefer-string-starts-ends-with": State.ON,
    "@typescript-eslint/promise-function-async": State.ON,
    "@typescript-eslint/related-getter-setter-pairs": State.ON,
    "@typescript-eslint/require-array-sort-compare": State.ON,
    "@typescript-eslint/restrict-plus-operands": [
      State.ON,
      {
        allowAny: false,
        allowBoolean: false,
        allowNullish: false,
        allowNumberAndString: false,
        allowRegExp: false,
      },
    ],
    "@typescript-eslint/restrict-template-expressions": [
      State.ON,
      {
        allowNullish: false,
        allowNever: false,
        allowRegExp: false,
      },
    ],
    "@typescript-eslint/return-await": State.ON /* BUG: doc incorrectly states that this extends the DEPRECATED (since 8.46) no-return-await: https://typescript-eslint.io/rules/return-await */,
    "@typescript-eslint/strict-boolean-expressions": [
      State.ON,
      {
        allowNullableObject: false,
        allowString: false,
      },
    ], /* requires tsconfig: strictNullChecks */
    "@typescript-eslint/switch-exhaustiveness-check": State.ON,
    // "@typescript-eslint/triple-slash-reference": State.OFF /* preference */,
    // "@typescript-eslint/typedef": State.OFF /* tsconfig: { noImplicitAny, strictPropertyInitialization } */,
    "@typescript-eslint/unbound-method": State.ON,
    "@typescript-eslint/unified-signatures": State.ON,
    "@typescript-eslint/use-unknown-in-catch-callback-variable": State.ON,
  } as const,
};
