export const
all = "all",
always = "always",
always_multiline = "always-multiline",
as_needed = "as-needed",
before = "before",
below = "below",
both = "both",
consecutive = "consecutive",
consistent = "consistent",
double = "double",
inside = "inside",
multi = "multi",
never = "never",
wildcard = "*";
