import { State } from "../state";

// DOC: https://ota-meshi.github.io/eslint-plugin-jsonc/rules/
export default {
  rules: {
    // "jsonc/auto": State.OFF,
    // "jsonc/key-name-casing": State.OFF,
    // "jsonc/no-bigint-literals": State.OFF,
    // "jsonc/no-binary-expression": State.OFF,
    // "jsonc/no-binary-numeric-literals": State.OFF,
    "jsonc/no-comments": State.ON,
    // "jsonc/no-escape-sequence-in-identifier": State.OFF,
    // "jsonc/no-hexadecimal-numeric-literals": State.OFF,
    // "jsonc/no-infinity": State.OFF,
    // "jsonc/no-nan": State.OFF,
    // "jsonc/no-number-props": State.OFF,
    // "jsonc/no-numeric-separators": State.OFF,
    // "jsonc/no-octal-numeric-literals": State.OFF,
    // "jsonc/no-parenthesized": State.OFF,
    // "jsonc/no-plus-sign": State.OFF,
    // "jsonc/no-regexp-literals": State.OFF,
    // "jsonc/no-template-literals": State.OFF,
    // "jsonc/no-undefined-value": State.OFF,
    // "jsonc/no-unicode-codepoint-escapes": State.OFF,
    // "jsonc/sort-array-values": State.OFF,
    // "jsonc/sort-keys": State.OFF /* ESLint: json/sort-keys */,
    // "jsonc/valid-json-number": State.OFF,
    // "jsonc/vue-custom-block/no-parsing-error": State.OFF,
    // "jsonc/array-bracket-newline": State.OFF /* BUG: DO NOT CONFIGURE */,
    "jsonc/array-bracket-spacing": State.WARN,
    "jsonc/array-element-newline": [
      State.WARN,
      "consistent",
    ],
    "jsonc/comma-dangle": State.ON,
    "jsonc/comma-style": State.WARN,
    "jsonc/indent": [
      State.WARN,
      2,
    ],
    "jsonc/key-spacing": State.WARN,
    "jsonc/no-dupe-keys": State.ON /* ESLint: json/no-duplicate-keys */,
    // "jsonc/no-floating-decimal": State.OFF,
    "jsonc/no-irregular-whitespace": [
      State.ON,
      {
        skipStrings: true,
        skipComments: true,
      },
    ],
    // "jsonc/no-multi-str": State.OFF,
    // "jsonc/no-octal-escape": State.OFF,
    // "jsonc/no-octal": State.OFF,
    // "jsonc/no-sparse-arrays": State.OFF,
    // "jsonc/no-useless-escape": State.OFF,
    "jsonc/object-curly-newline": [
      State.WARN,
      {
        consistent: true,
        multiline: true,
        minProperties: 2,
      },
    ],
    "jsonc/object-curly-spacing": [
      State.WARN,
      "always",
    ],
    "jsonc/object-property-newline": State.WARN,
    // "jsonc/quote-props": State.OFF,
    // "jsonc/quotes": State.OFF,
    // "jsonc/space-unary-ops": State.OFF,
  } as const,
};
