import {
  ID,
  OFF,
} from "../../_strings";

export const SvelteDisable = [
  ID.Disable,
  {
    // Copied from Svelte base config:
    // DOC: https://github.com/sveltejs/eslint-plugin-svelte/blob/ca37fbbe82d01019946e12eeb1b57c2a5736c018/packages/eslint-plugin-svelte/src/configs/base.ts

    /* ESLint core rules known to cause problems with `.svelte`. */
    "no-inner-declarations": OFF /* The AST generated by svelte-eslint-parser will false positives in it rule because the root node of the script is not the `Program`. */,
    // "no-irregular-whitespace": OFF /* INFO: This is commented out in the config as well */,
    "no-self-assign": OFF /* Self assign is one of way to update reactive value in Svelte */,
    "prefer-const": OFF /* svelte/prefer-const */,
  } as const,
] as const;
