import { State } from "../state";

// DOC: https://github.com/sveltejs/eslint-plugin-svelte/blob/ca37fbbe82d01019946e12eeb1b57c2a5736c018/packages/eslint-plugin-svelte/src/configs/base.ts
export default {
  rules: {
    // ESLint core rules known to cause problems with `.svelte`.
    "no-inner-declarations": State.OFF /* The AST generated by svelte-eslint-parser will false positive because the root node of the script is not `Program`. INFO: also extended by svelte  */,
    "no-self-assign": State.OFF /* Self assign is one of way to update reactive value in Svelte. */,
    "no-unused-vars": State.OFF /* breaks use of svelte global */,
    "ts/no-unused-vars": State.OFF /* TS: breaks use of svelte global */,
    "prefer-const": State.OFF /* svelte/prefer-const */,
    // My own
    "stylistic/indent": State.OFF /* Conflicts with `svelte/indent` */,
    "ts/no-confusing-void-expression": State.OFF /* errors on render() */,
  } as const,
};
